name: GitHub Actions Demo
run-name: Deploy Staging Demo 🚀
on: 
  push:
    branches: [staging]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    
    step:
      - users: actions/checkout@v3
      - name: Use Node.js
        users: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install
      - run: yarn run build --if-present
      - run: yarn test