name: GitHub Actions Demo
run-name: Deploy Staging Demo 🚀
on: 
  push:
    branches: [staging]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install
      - run: yarn build 
      - run: yarn test